[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = "netlify/edge-functions"
  environment = { CI = "true" }  # Forza modalità CI per build più dettagliate

[[plugins]]
  # package = "@netlify/plugin-image-optimization"
  [plugins.inputs]
  disabled = true

[context.production.environment]
  NODE_ENV = "development"

[context.deploy-preview.environment]
  NODE_ENV = "development"