[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = "netlify/edge-functions"
  environment = { CI = "true" }  # Forza modalità CI per build più dettagliate

[context.production.environment]
  NODE_ENV = "development"

[context.deploy-preview.environment]
  NODE_ENV = "development"