[build]
  command = "npm run build"
  publish = "dist"

  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

